# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: Windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar'
    organization: 'dev-nikky'
    scannerMode: 'MSBuild'
    projectKey: 'nikky1990'
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
